### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by cfcs** [robur-coop/dnsvizor#1]
first

- [x] DNS boot params (first): upstream resolver (IP) #3
- [x] use dns-stub library
- [x] one network interface (upstream + downstream), listen on UDP/53 and TCP/53
- [ ] documentation: Configuration, overall system design
- [x] CI #2

later
- [ ] DNS request timeouts (see https://github.com/mirage/ocaml-dns/issues/216)
- [x] bundle DHCP and DNS server into one (no pi-hole, no DNS-over-TLS)
- [ ] DHCP boot params (second): IP range for leases; default gateway, local domain name
- [ ] DHCP server lease database (needs some cleanup work), also collect garbage (free leases)
- [ ] leases are stored (salted hash of the mac address) as DHCID DNS resource records (where the TTL is equal to the DHCP lease time)

**Comment by hannesm** [comment]
This is a bit dated, and overcome by events. Though likely we'll solve some of the tasks here in the process. I'll close to avoid confusion.
