### ISSUE TITLE
Support dnsmasq options listen-address and bind-interfaces

### ISSUE THREAD

**Issue by reynir** [robur-coop/dnsvizor#16]
In a >10 year old dnsmasq configuration used with openvpn I have the following configuration:
```
listen-address=127.0.0.1,10.8.0.1
bind-interfaces
```

**Comment by reynir** [comment]
As they are not so meaningful in a DNSvizor context I think we can either ignore them or not implement them. I guess it depends what the expectation is - would the user expect any configuration to (best effort) work with DNSvizor? Or can we expect them to do (minor) modifications to their configuration for things that don't make sense with DNSvizor? I think the latter would be nicer from a developer perspective, but from a user perspective it may be nicer with the former as they then don't have to 1) understand the configuration in detail, 2) don't have to bother with the finer nuances of dnsmasq vs DNSvizor.

**Comment by hannesm** [comment]
done in #20
